data_root: "D:/duong_huy_ct7/deepfake-data"
train_dir: "train"
val_dir: "val"
test_dir: "test"
cross_dataset_root: "D:/duong_huy_ct7/deepfake-data/celeb-df/test"
gan_fake_dir: "F:/DeepFakedata/chien_duy_thinh_output/gan_data/generated_fake_2"
gan_real_dir: "F:/DeepFakedata/chien_duy_thinh_output/gan_data/generated_real"

image_size: 224
batch_size: 16
num_workers: 4
epochs: 30
lr: 1e-4
weight_decay: 1e-4
dropout: 0.4
pretrained: true
backbone: "efficientnetb4"  # options: efficientnetb4, resnet50, swin_tiny, swin_small
original_upsample_factor: 3
train_real_percent: 100  # use 0-100% of original images in train_dir/original
save_dir: "checkpoints_efficientnetb4"
checkpoint_name: "best_efficientnetb4.pth"
gan_save_dir: "checkpoints_efficientnetb4"
gan_checkpoint_name: "best_efficientnetb4_gan.pth"
resume_from: null
seed: 42
threshold: 0.5
device: "cuda"

early_stopping_patience: 5
lr_scheduler_patience: 2
lr_scheduler_factor: 0.5
min_lr: 1e-7
